#!/bin/bash
# Finish restoring opted-in stacks before Docker/libvirt and VM autostart.
source /usr/local/emhttp/plugins/my-unraid-vgpu-manager/include/common.sh
trim_log "/var/log/${PLUGIN}-boot.log"
"$EMHTTP/scripts/rc.vgpu" ensure >>"/var/log/${PLUGIN}-boot.log" 2>&1
