#!/bin/bash
# Allowlisted UI operations. Failures retain their exit status all the way to UI.
source "$(dirname "$(readlink -f "$0")")/common.sh"
RC="$EMHTTP/scripts/rc.vgpu"

UPDATE_CRON=/usr/local/sbin/update_cron
CRONFILE="${PLGCFG}/${PLUGIN}.cron"

cron_entries() {
  printf '# Generated by %s\n' "$PLUGIN"
  if [ "$(setting update_check)" = true ]; then
    printf '17 9 * * * %s/include/update-check.sh >/dev/null 2>&1\n' "$EMHTTP"
  fi
  # OS updates still need a notification when automatic preparation is off.
  printf '* * * * * %s/include/upgrade-check.sh auto >>/var/log/%s-upgrade.log 2>&1\n' "$EMHTTP" "$PLUGIN"
}

without_plugin_entries() {
  grep -Fv -- "$EMHTTP/include/update-check.sh" | grep -Fv -- "$EMHTTP/include/upgrade-check.sh" |
    grep -Fxv -- "# Generated by $PLUGIN"
}

# Unraid rebuilds the system crontab from registered plugins' .cron files
# whenever a schedule changes or a plugin is removed, discarding entries added
# with crontab directly. Publish a .cron file and let update_cron install it.
configure_cron() {
  local tmp current
  mkdir -p "$PLGCFG" || return 1
  tmp="$(mktemp)" || return 1
  cron_entries > "$tmp" || { rm -f "$tmp"; return 1; }
  if ! cmp -s "$tmp" "$CRONFILE"; then
    cat "$tmp" > "$CRONFILE" || { rm -f "$tmp"; return 1; }
  fi
  if [ ! -x "$UPDATE_CRON" ]; then
    # Outside Unraid: maintain the entries in the user crontab.
    { crontab -l 2>/dev/null | without_plugin_entries; cat "$tmp"; } > "${tmp}.tab"
    crontab "${tmp}.tab"
    local result=$?
    rm -f "$tmp" "${tmp}.tab"
    return "$result"
  fi
  rm -f "$tmp"
  # Drop entries that older versions added directly.
  current="$(crontab -l 2>/dev/null)"
  if grep -Fq -- "$EMHTTP/include/" <<< "$current"; then
    without_plugin_entries <<< "$current" | crontab - || return 1
  fi
  if [ -e "/var/log/plugins/${PLUGIN}.plg" ]; then
    "$UPDATE_CRON"
  else
    # During installation the plugin is registered only after this script
    # finishes, and update_cron ignores unregistered plugins until then.
    nohup bash -c 'for _ in $(seq 120); do
        [ -e "/var/log/plugins/$1.plg" ] && exec "$2"; sleep 1
      done' _ "$PLUGIN" "$UPDATE_CRON" >/dev/null 2>&1 9>&- &
  fi
}

change_update_check() {
  case "${1:-}" in true|false) ;; *) return 1 ;; esac
  set_setting update_check "$1" && configure_cron
}

install_nvidia() {
  local series="${1:-$(nvidia_series)}" pkg
  series_prefix "$series" >/dev/null || return 1
  operation_lock || return 1
  "$EMHTTP/include/download.sh" nvidia "$series" latest || return 1
  pkg="$(find_package nvidia "$KERNEL_V" "$series")" || return 1
  "$RC" nvidia_install "$pkg"
  save_nvidia_choice "$?" "$pkg" "$series" latest
}

# Keep the series and version preference unchanged unless the package was
# actually installed; a failed switch must not redirect later upgrades.
save_nvidia_choice() {
  local result="$1" pkg="$2" series="$3" want="$4"
  if [ "$(installed_package nvidia)" = "${pkg##*/}" ]; then
    set_setting nvidia_series "$series" && set_setting driver_version "$want" || return 1
  fi
  return "$result"
}

update_driver() {
  local series="${1:-$(nvidia_series)}" want="${2:-latest}" pkg
  series_prefix "$series" >/dev/null && valid_version "$want" || return 1
  [ "$(setting nvidia_installed)" = true ] || { echo 'ERROR: NVIDIA is not enabled'; return 1; }
  operation_lock || return 1
  "$EMHTTP/include/download.sh" nvidia "$series" "$want" --refresh || return 1
  pkg="$(find_package nvidia "$KERNEL_V" "$series" "$want")" || return 1
  "$RC" nvidia_update "$pkg"
  save_nvidia_choice "$?" "$pkg" "$series" "$want"
}

install_intel() {
  local pkg
  operation_lock || return 1
  "$EMHTTP/include/download.sh" i915 latest || return 1
  pkg="$(find_package i915 "$KERNEL_V")" || return 1
  "$RC" intel_install "$pkg"
}

update_intel() {
  local pkg
  [ "$(setting intel_installed)" = true ] || { echo 'ERROR: Intel is not enabled'; return 1; }
  operation_lock || return 1
  "$EMHTTP/include/download.sh" i915 latest --refresh || return 1
  pkg="$(find_package i915 "$KERNEL_V")" || return 1
  "$RC" intel_install "$pkg"
}

case "${1:-}" in
  configure_cron) configure_cron; exit $? ;;
  change_update_check) change_update_check "${2:-}"; exit $? ;;
  get_boot_kernel) exec php "$EMHTTP/include/kernel.php" ;;
  prepare_kernel) exec "$EMHTTP/include/upgrade-check.sh" prepare "${2:-}" ;;
  install_nvidia|update_driver|install_intel|update_intel)
    action="$1"; shift; "$action" "$@"; result=$? ;;
  uninstall_nvidia) "$RC" nvidia_uninstall; result=$? ;;
  uninstall_intel) "$RC" intel_uninstall; result=$? ;;
  restart_services) "$RC" restart; result=$? ;;
  apply_devices) "$RC" apply; result=$? ;;
  *) echo 'ERROR: unknown operation' >&2; exit 1 ;;
esac
if [ "$result" = 0 ]; then
  bilingual 'Operation completed. Close this window to refresh the status.' '操作完成，关闭窗口后刷新状态。'
else
  bilingual 'ERROR: operation failed. Check the messages above before retrying.' '错误：操作未完成，请查看上方日志后重试。' >&2
fi
exit "$result"
